changelog:
  exclude:
    labels:
      - skip-changelog
      - duplicate
      - invalid
  categories:
    - title: Features
      labels:
        - feature
        - enhancement
    - title: Fixes
      labels:
        - bug
        - fix
    - title: Privacy & Security
      labels:
        - privacy
        - security
    - title: Accessibility
      labels:
        - accessibility
    - title: Performance
      labels:
        - performance
    - title: Documentation
      labels:
        - documentation
        - docs
    - title: Dependencies
      labels:
        - dependencies
    - title: Maintenance
      labels:
        - "*"
