name: Release Drafter

on:
  push:
    branches: [main]
  pull_request_target:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update-release-draft:
    name: Update release draft
    if: github.event_name != 'pull_request_target'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      - name: Update draft release
        uses: release-drafter/release-drafter@34d80673e067bdc0c24568d3af899c216adcfaa9 # v7
        with:
          config-name: release-drafter.yml

  label-pull-request:
    name: Label pull request
    if: github.event_name == 'pull_request_target'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Apply release labels
        uses: release-drafter/release-drafter/autolabeler@d749bd2b1d1e1db5c7a422e645f7e4ec23f604e3 # v7
        with:
          config-name: release-drafter.yml
